// Fixed catalog of IT job roles. Each role carries the baseline ("basic value")
// requirements a resume is analyzed against — no user-authored job postings.
const ROLES = [
  { id: 'frontend-developer', title: 'Frontend Developer',
    mustHaveSkills: ['javascript', 'react', 'html', 'css'],
    niceToHaveSkills: ['typescript', 'next.js', 'figma', 'sass'],
    minExperienceYears: 2 },
  { id: 'backend-developer', title: 'Backend Developer',
    mustHaveSkills: ['node.js', 'sql', 'rest api'],
    niceToHaveSkills: ['docker', 'aws', 'graphql', 'microservices', 'git'],
    minExperienceYears: 2 },
  { id: 'fullstack-developer', title: 'Full Stack Developer',
    mustHaveSkills: ['javascript', 'react', 'node.js', 'sql'],
    niceToHaveSkills: ['typescript', 'docker', 'aws'],
    minExperienceYears: 3 },
  { id: 'mobile-developer', title: 'Mobile App Developer',
    mustHaveSkills: ['kotlin', 'android'],
    niceToHaveSkills: ['swift', 'ios', 'flutter', 'react native', 'firebase'],
    minExperienceYears: 2 },
  { id: 'devops-engineer', title: 'DevOps Engineer',
    mustHaveSkills: ['docker', 'kubernetes', 'ci/cd'],
    niceToHaveSkills: ['terraform', 'aws', 'ansible', 'linux', 'prometheus'],
    minExperienceYears: 3 },
  { id: 'sre', title: 'Site Reliability Engineer',
    mustHaveSkills: ['linux', 'monitoring', 'incident response'],
    niceToHaveSkills: ['kubernetes', 'prometheus', 'grafana', 'aws', 'python'],
    minExperienceYears: 3 },
  { id: 'cloud-engineer', title: 'Cloud Engineer',
    mustHaveSkills: ['aws', 'terraform'],
    niceToHaveSkills: ['azure', 'gcp', 'kubernetes', 'docker', 'linux'],
    minExperienceYears: 3 },
  { id: 'data-engineer', title: 'Data Engineer',
    mustHaveSkills: ['python', 'sql', 'etl'],
    niceToHaveSkills: ['spark', 'airflow', 'hadoop', 'kafka', 'aws'],
    minExperienceYears: 2 },
  { id: 'data-scientist', title: 'Data Scientist',
    mustHaveSkills: ['python', 'data science', 'pandas'],
    niceToHaveSkills: ['machine learning', 'numpy', 'sql', 'tableau'],
    minExperienceYears: 2 },
  { id: 'data-analyst', title: 'Data Analyst',
    mustHaveSkills: ['sql', 'excel', 'data visualization'],
    niceToHaveSkills: ['python', 'tableau', 'power bi', 'communication'],
    minExperienceYears: 1 },
  { id: 'ml-engineer', title: 'Machine Learning Engineer',
    mustHaveSkills: ['python', 'machine learning', 'tensorflow'],
    niceToHaveSkills: ['pytorch', 'scikit-learn', 'keras', 'numpy', 'pandas'],
    minExperienceYears: 3 },
  { id: 'ai-engineer', title: 'AI / NLP Engineer',
    mustHaveSkills: ['python', 'nlp', 'machine learning'],
    niceToHaveSkills: ['pytorch', 'llm', 'prompt engineering', 'tensorflow'],
    minExperienceYears: 2 },
  { id: 'qa-engineer', title: 'QA / Test Automation Engineer',
    mustHaveSkills: ['selenium', 'automation testing'],
    niceToHaveSkills: ['cypress', 'jest', 'junit', 'manual testing', 'jira'],
    minExperienceYears: 2 },
  { id: 'cybersecurity-engineer', title: 'Cybersecurity Engineer',
    mustHaveSkills: ['cybersecurity', 'networking'],
    niceToHaveSkills: ['penetration testing', 'siem', 'firewall', 'iam', 'linux'],
    minExperienceYears: 3 },
  { id: 'network-engineer', title: 'Network Engineer',
    mustHaveSkills: ['networking', 'tcp/ip'],
    niceToHaveSkills: ['dns', 'firewall', 'linux', 'cybersecurity'],
    minExperienceYears: 3 },
  { id: 'dba', title: 'Database Administrator',
    mustHaveSkills: ['sql', 'database administration'],
    niceToHaveSkills: ['oracle', 'postgresql', 'mysql', 'aws'],
    minExperienceYears: 3 },
  { id: 'technical-pm', title: 'Technical Product Manager',
    mustHaveSkills: ['project management', 'roadmap', 'stakeholder management'],
    niceToHaveSkills: ['agile', 'scrum', 'jira', 'communication'],
    minExperienceYears: 3 },
  { id: 'ui-ux-designer', title: 'UI/UX Designer',
    mustHaveSkills: ['figma', 'ui design', 'ux design'],
    niceToHaveSkills: ['wireframing', 'user research', 'prototyping', 'sketch', 'adobe xd'],
    minExperienceYears: 2 },
  { id: 'blockchain-developer', title: 'Blockchain Developer',
    mustHaveSkills: ['solidity', 'blockchain'],
    niceToHaveSkills: ['ethereum', 'web3', 'smart contracts', 'javascript'],
    minExperienceYears: 2 },
  { id: 'game-developer', title: 'Game Developer',
    mustHaveSkills: ['unity', 'c#'],
    niceToHaveSkills: ['unreal engine', 'game design', 'c++', 'git'],
    minExperienceYears: 2 },
];

function listRoles() {
  return ROLES;
}

function getRole(id) {
  return ROLES.find(r => r.id === id);
}

module.exports = { ROLES, listRoles, getRole };
